version: '3.8'

services:
  wol:
    image: dabondi/go-rest-wol
    container_name: wol
    ports:
      - "9090:9090"
    environment:
      - WOLHTTPPORT=9090
    volumes:
      - ./config/computers.csv:/app/computer.csv
    restart: unless-stopped
