---

#volumes:
#  vol-1:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=nas-prod-1.home.clcreative.de,rw,vers=4.1
#      device: ":/mnt/store/app-pv/homepage-prod-1-vol-1"
#  vol-2-images:
#    driver: local
#   driver_opts:
#      type: nfs
#      o: addr=nas-prod-1.home.clcreative.de,rw,vers=4.1
#      device: ":/mnt/store/app-pv/homepage-prod-1-vol-2/images"
#  vol-2-icons:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=nas-prod-1.home.clcreative.de,rw,vers=4.1
#      device: ":/mnt/store/app-pv/homepage-prod-1-vol-2/icons"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
     - frontend
    #  - backend
    # ports:
    #   - 3000:3000
    environment:
      - LOG_LEVEL=debug
      - HOMEPAGE_VAR_PROXMOX_USERNAME=${HOMEPAGE_VAR_PROXMOX_USERNAME}
      - HOMEPAGE_VAR_PROXMOX_PASSWORD=${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      - HOMEPAGE_VAR_TRUENAS_KEY=${HOMEPAGE_VAR_TRUENAS_KEY}
      - HOMEPAGE_VAR_PORTAINER_KEY=${HOMEPAGE_VAR_PORTAINER_KEY}
      - HOMEPAGE_VAR_AUTHENTIK_KEY=${HOMEPAGE_VAR_AUTHENTIK_KEY}
      - HOMEPAGE_VAR_HOMEASSISTANT_KEY=${HOMEPAGE_VAR_HOMEASSISTANT_KEY}
      - HOMEPAGE_ALLOWED_HOSTS=dash.siri.naralab.cloud
    volumes:
      - /root/homepage-prod-1/config:/app/config
      - /root/homepage-prod-1/icons:/app/public/images
      - /root/homepage-prod-1/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
     traefik.enable: "true"
    #  traefik.http.routers.homepage-prod-1-http.entrypoints: "web"
    #  traefik.http.routers.homepage-prod-1-http.rule: "Host(`dash.siri.naralab.cloud`)"
     traefik.http.routers.homepage-prod-1-https.entrypoints: "websecure"
     traefik.http.routers.homepage-prod-1-https.rule: "Host(`dash.siri.naralab.cloud`)"
     traefik.http.routers.homepage-prod-1-https.tls: "true"
     traefik.http.routers.homepage-prod-1-https.tls.certresolver: "cloudflare"
networks:
 frontend:
   external: true
 backend:
   external: true