---
- Repositories:
  - Portainer:
    - icon: /icons/portainer1.webp
      href: https://portainer.siri.naralab.cloud
  - PiHole:
    - icon: /icons/pihole.svg
      href: https://pihole2.siri.naralab.cloud/admin/login
  - Nessus:
    - icon: /icons/nessus1.png
      href: https://nessus.siri.naralab.cloud/#/
  - Wazuh:
    - icon: /icons/wazuh1.png
      href: https://wazuh.siri.naralab.cloud/app/login?
  - Rancher:
    - icon: /icons/rancher.png
      href: http://192.168.15.252:980
      
  # - Wazuh:
  #   - icon: /icons/wazuh1.png
  #     href: https://wazuh.siri.naralab.cloud/app/login

# - Cloud Services:
#   - Sophos Cloud:
#     - icon: /icons/cld.png
#       href: https://cloud.sophos.com
#   - Cloudflare:
#     - icon: cloudflare.png
#       href: https://dash.cloudflare.com
#   - Teleport:
#     - icon: teleport.png
#       href: https://clcreative.teleport.sh
#   - Twingate:
#     - icon: twingate.png
#       href: https://clcreative.twingate.com
#   - Netbird:
#     - icon: https://netbird.io/_next/static/media/netbird-icon.00225e97.svg
#       href: https://app.netbird.io

# - Cloud Platforms:
#   - Microsoft Azure:
#     - icon: azure.png
#       href: https://portal.azure.com
#   - Digital Ocean:
#     - icon: si-digitalocean-#0080FF
#       href: https://cloud.digitalocean.com
#   - CIVO:
#     - icon: si-civo-#239DFF
#       href: https://www.civo.com
